# action.yml
name: 'Semantic Version Information'
description: 'Version and branch information useful for semantic versioning'
branding:
    icon: 'git-branch'
    color: 'black'
outputs:
  branch:
    description: 'Current branch name. Base branch if in a PR.'
  branch_alpha:
    description: 'Branch name with only alphanumbers. Valid to use with image paths for example.'
  version:
    description: 'Next semantic version. Based on /VERSION and branch name.'
runs:
  using: 'docker'
  image: 'Dockerfile'
