on: [push]

jobs:
  current-branch-job:
    runs-on: ubuntu-latest
    name: Test action
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Bump version
      uses: remorses/bump-version@js
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master

    - name: Use action
      id: semver
      uses: shelmangroup/semver-info@work

    - name: Echo outputs
      run: |
        echo "branch=${{ steps.semver.outputs.branch }}"
        echo "branch_alpha=${{ steps.semver.outputs.branch_alpha }}"
        echo "version_current=${{ steps.semver.outputs.version_current }}"
        echo "VER=${{ steps.derive-version.outputs.version }}+${{ steps.semver.outputs.branch_alpha }}.${GITHUB_RUN_NUMBER}"
